services:

  # NGINX REVERSE PROXY
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy-dev
    ports:
      # El Ãºnico que expone puertos a la VM
      - "80:80"
      - "443:443"
    volumes:
      # Monta el archivo de config de Nginx
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      # Monta los certificados SSL (solo lectura)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    depends_on:
      - auth-api-dev
      - engine-api-dev
      - snippet-api-dev
      - printscript-ui-dev

  ## DEV enviroment
  auth-api-dev:
    image: ghcr.io/ing-sist/auth-api-dev:latest
    container_name: auth-api-dev
    env_file:
      -  .env
    expose:
      - 8080
    depends_on:
      auth-postgres-db-dev:
        condition: service_healthy

  auth-postgres-db-dev:
    image: ghcr.io/ing-sist/auth-postgres-db-dev
    container_name: auth-postgres-db-dev
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  engine-api-dev:
    image: ghcr.io/ing-sist/engine-api-dev:latest
    container_name: engine-api-dev
    env_file:
      - .env
    expose:
      - 8081
    depends_on:
      engine-postgres-db-dev:
        condition: service_healthy
  engine-postgres-db-dev:
    image: ghcr.io/ing-sist/engine-postgres-db-dev
    container_name: engine-postgres-db-dev
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  snippet-api-dev:
    image: ghcr.io/ing-sist/snippet-api-dev:latest
    container_name: snippet-api-dev
    env_file:
      - .env
    expose:
      - 8082
    depends_on:
      snippet-postgres-db-dev:
        condition: service_healthy
  snippet-postgres-db-dev:
    image: ghcr.io/ing-sist/snippet-postgres-db-dev
    container_name: snippet-postgres-db-dev
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  printscript-ui-dev:
    image: ghcr.io/ing-sist/printscript-ui-dev:latest
    container_name: printscript-ui-dev
    expose:
      - 80
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"

  asset-service:
    container_name: asset_service_dev
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false
    ports:
      - "8080:8080"
    restart: unless-stopped
