services:

  # NGINX REVERSE PROXY

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy-dev
    ports:
      # El único que expone puertos a la VM
      - "80:80"
      - "443:443"
    volumes:
      # 1. Monta el archivo de config de Nginx
      - ./nginx.conf/server.dev.conf:/etc/nginx/conf.d/default.conf:ro
      # 2. Certificados SSL (Solo lectura)
      - ./certbot/conf:/etc/letsencrypt:ro
      # 3. Desafío Webroot (Solo lectura)
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - auth-service-dev
      - engine-service-dev
      - snippet-service-dev
      - printscript-ui-dev


  # === DUCKDNS (DEV) ===

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 # ID usuario estandar linux
      - PGID=1000 # ID grupo estandar linux
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN_DEV}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped

  # === CERTBOT (Generador SSL) ===
  # Se encarga de crear y renovar los certificados automáticamente

  certbot:
    image: certbot/certbot
    container_name: certbot-dev
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "if [ -f /etc/letsencrypt/live/${DUCKDNS_SUBDOMAIN_DEV}.duckdns.org/fullchain.pem ]; then certbot renew --webroot -w /var/www/certbot --quiet; else certbot certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} -d ${DUCKDNS_SUBDOMAIN_DEV}.duckdns.org --agree-tos --no-eff-email; fi"
    depends_on:
      - nginx-proxy

  # === MICROSERVICIOS Y BASES DE DATOS ===

  auth-service-dev:
    image: ghcr.io/ing-sist/auth-service:dev-latest
    container_name: auth-service-dev
    env_file:
      -  .env
    environment:
      POSTGRES_DB: ${AUTH_DATABASE_URL}
      POSTGRES_USER: ${AUTH_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
    expose:
      - 8084
    depends_on:
      auth-service-db-dev:
        condition: service_healthy

  auth-service-db-dev:
    image: postgres:17.6-alpine
    container_name: auth-service-db-dev
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - auth_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AUTH_DATABASE_URL}
      POSTGRES_USER: ${AUTH_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  snippet-service-dev:
    image: ghcr.io/ing-sist/snippet-service:newrelic-test
    container_name: snippet-service-dev
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SNIPPET_DATABASE_URL}
      POSTGRES_USER: ${SNIPPET_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SNIPPET_DATABASE_PASSWORD}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_ENVIRONMENT: development
#      NEW_RELIC_APP_NAME: "Snippet Service (Development)"
    ports:
      - "8082:8080"
    expose:
      - 8082
    depends_on:
      snippet-service-db-dev:
        condition: service_healthy

  snippet-service-db-dev:
    image: postgres:17.6-alpine
    container_name: snippet-service-db-dev
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SNIPPET_DATABASE_URL}
      POSTGRES_USER: ${SNIPPET_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SNIPPET_DATABASE_PASSWORD}
    volumes:
      - snippet_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  engine-service-dev:
    image: ghcr.io/ing-sist/engine-service:dev-latest
    container_name: engine-service-dev
    env_file:
      - .env
    expose:
      - 8081

  printscript-ui-dev:
    image: ghcr.io/ing-sist/printscript-ui-dev:latest
    container_name: printscript-ui-dev
    expose:
      - 80
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"

  asset-service:
    container_name: asset_service_dev
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: "false"
    ports:
      - "8080:8080"
    restart: unless-stopped


  redis-dev:
    container_name: event-bus
    image: redis:6-alpine
    command: redis-server --appendonly yes # guardar cada operacion en disco
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  auth_data_dev:
  snippet_data_dev:
  redis_data_dev:
