name: Deploy Infra Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SNIPPET_VM_DEV_IP }}
          username: ${{ secrets.SNIPPET_VM_DEV_USER }}
          key: ${{ secrets.SNIPPET_VM_DEV_SSH_KEY }}
          script: |
            # 1. Navegar a la carpeta del repo
            cd ~/ing-sist/infra
            
            # 2. Asegurarnos de estar en la rama correcta
            git fetch origin
            git checkout dev
            git pull origin dev
            
            # 3. Bajar los contenedores viejos
            docker-compose -f docker-compose.dev.yml down 
            
            # 4. Levantar todo actualizado        
            docker-compose -f docker-compose.dev.yml up -d --build
            
            # 5. Limpiar im√°genes viejas para no llenar el disco
            docker image prune -f

